export type ManagerLocale = "en" | "zh";
export type TranslationKey = "summary" | "eyebrow" | "title" | "intro" | "loading" | "configurationLoaded" | "noUsableConfig" | "unableLoad" | "configurationSaved" | "unableSave" | "permissionsRepaired" | "repairPermissions" | "unableRepair" | "localServerFound" | "authMode" | "localManagementAvailable" | "noLocalRootKey" | "invalidConfig" | "endpoint" | "endpointRequiredFirst" | "account" | "user" | "newUserKey" | "optional" | "existingKey" | "pasteUserKey" | "keyHint" | "save" | "verify" | "openStudio" | "unreachable" | "notReady" | "keyNotAccepted" | "connectedAs" | "recoverTitle" | "recoverHint" | "temporaryRootKey" | "pasteRootKey" | "listAccounts" | "listAccountsTitle" | "listAccountsHint" | "clearRootKey" | "rootKeyCleared" | "selectAccount" | "selectUser" | "chooseAccount" | "chooseUser" | "foundAccounts" | "foundUsers" | "rootKeyRequired" | "adminFailed" | "createAccountTitle" | "createAccountHint" | "createAccount" | "createUserTitle" | "createUserHint" | "createUser" | "noAccountsLoaded" | "regenerateTitle" | "regenerateHint" | "regenerateKey" | "accountId" | "userId" | "adminOperationComplete" | "keyRotated" | "toggleLabel" | "toggleStateOn" | "toggleStateOff" | "toggleAction" | "toggleFailed" | "aboutTitle" | "openRepository" | "checkUpdates" | "checkingUpdates" | "updateAvailable" | "upToDate" | "updateCheckFailed" | "viewRelease" | "isolationTitle" | "isolateByTopicLabel" | "isolationHint" | "isolationSaved" | "isolationSaveFailed" | "envOverrideWarning" | "peerIdLabel" | "peerIdPlaceholder" | "peerIdHint" | "peerIdHintEmpty" | "peerIdHintSet" | "peerIdMultiRepoNotice" | "peerIdEnvWarning" | "peerIdCredentialWarning" | "fillCurrentRepo" | "peerIdDetected" | "peerIdNotInRepo" | "peerIdSaved" | "peerIdSaveFailed" | "savePeerId" | "peerIdReloadNotice" | "reloadNotice" | "reloading" | "restartSucceeded" | "restartUnavailable" | "restartFailed" | "tuningTitle" | "tuningIntro" | "scoreThresholdLabel" | "scoreThresholdHint" | "recallLimitLabel" | "recallLimitHint" | "queryExpansionLabel" | "queryExpansionHint" | "queryExpansionAuto" | "queryExpansionOff" | "excludeUrisLabel" | "excludeUrisHint" | "defaultPlaceholder" | "saveTuning" | "tuningSaved" | "tuningSaveFailed" | "tuningEnvWarning" | "tuningReloadNotice";
export type Translation = (key: TranslationKey, params?: Record<string, string | number>) => string;
export declare const dictionaries: {
    readonly en: Record<TranslationKey, string>;
    readonly zh: Record<TranslationKey, string>;
};
export declare function localeFrom(value: string | undefined): ManagerLocale;
export declare function browserLocale(): ManagerLocale;
export declare function createTranslation(locale: string | undefined): Translation;
