export const managerCss = `
.ovm-recovery>summary{cursor:pointer;list-style:none}.ovm-recovery>summary::-webkit-details-marker{display:none}.ovm-recovery>summary::after{content:"+";float:right;color:var(--dsw-alias-label-tertiary,#77818b);font-size:20px;line-height:18px}.ovm-recovery[open]>summary::after{content:"−"}.ovm-recoveryContent{display:grid;gap:14px;margin-top:18px}.ovm-adminTabs{display:flex;gap:4px;overflow-x:auto;border-bottom:1px solid var(--dsw-alias-border-l2,#dce1e6)}.ovm-adminTab{flex:0 0 auto;border:0;border-bottom:2px solid transparent;background:transparent;color:var(--dsw-alias-label-secondary,#59636e);padding:8px 10px;font:inherit;font-size:13px}.ovm-adminTab:hover{background:var(--dsw-alias-bg-layer-1,#f6f8fa)}.ovm-adminTabActive{border-bottom-color:#1f5d50;color:#1f4038;font-weight:600}.ovm-adminTabs+div .ovm-adminForm{margin-top:14px}
.ovm-shell{max-width:760px;padding:28px;color:var(--dsw-alias-label-primary,#202124);font-family:ui-sans-serif,system-ui,sans-serif}.ovm-eyebrow{color:#2f6f5e;font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}.ovm-shell h1{margin:4px 0 10px;font-size:28px;letter-spacing:-.03em}.ovm-intro{max-width:620px;color:var(--dsw-alias-label-secondary,#59636e);line-height:1.65}.ovm-card{margin-top:24px;border:1px solid var(--dsw-alias-border-l2,#dce1e6);border-radius:12px;background:var(--dsw-alias-bg-layer-2,#fff);padding:20px}.ovm-status{margin-bottom:16px;color:#365b4f;font-size:13px}.ovm-warning{display:flex;align-items:center;justify-content:space-between;gap:12px;border-left:3px solid #b47d1f;background:#fff8e8;padding:12px;color:#664500;font-size:13px}.ovm-warning button{background:#fff;border:1px solid #b47d1f;color:#664500}form{display:grid;gap:14px;margin-top:18px}label{display:grid;gap:6px;color:var(--dsw-alias-label-primary,#202124);font-size:13px;font-weight:600}input,select{height:36px;border:1px solid var(--dsw-alias-border-l2,#ccd3da);border-radius:7px;padding:0 10px;background:transparent;color:inherit;font:inherit;font-weight:400}.ovm-optional,.ovm-hint{color:var(--dsw-alias-label-tertiary,#77818b);font-weight:400}.ovm-hint{margin:0;font-size:12px;line-height:1.5}.ovm-actions{display:flex;align-items:center;gap:14px;margin-top:8px}.ovm-actions button,.ovm-actions a,.ovm-adminForm button{border-radius:7px;padding:8px 13px;font:inherit;font-size:13px;text-decoration:none}.ovm-actions button,.ovm-adminForm button{border:0;background:#1f4038;color:#fff}.ovm-actions .ovm-secondary{border:1px solid #1f4038;background:transparent;color:#1f4038}.ovm-actions a{color:#1f5d50}.ovm-actions button:disabled,.ovm-adminForm button:disabled{opacity:.55}.ovm-card h2{margin:0 0 8px;font-size:18px}.ovm-adminGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px;margin-top:18px}.ovm-adminForm{border:1px solid var(--dsw-alias-border-l2,#dce1e6);border-radius:8px;padding:14px}.ovm-adminForm h3{margin:0;font-size:14px}.ovm-danger{background:#9d2d2d!important}
`;

export function installManagerStyles(): void {
  if (typeof document === "undefined" || document.querySelector("style[data-plugin='dsh-openviking-manager']") !== null) return;
  const tag = document.createElement("style");
  tag.dataset.plugin = "dsh-openviking-manager";
  tag.textContent = managerCss;
  document.head.appendChild(tag);
}
